# Do NOT update manually; changes here will be overwritten by Copier
_commit: fd8dbb0
_src_path: https://github.com/itbrasil-odoo/itbrasil-addons-repo-template.git
additional_ruff_rules: []
banner_url: https://itbrasil.com.br/web/image/24368-93015bbb/readme-banner-image.png
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 19.0
org_name: IT Brasil
org_slug: itbrasil-odoo
postgres_image: ''
rebel_module_groups: []
repo_description: Addons to improve Odoo usability
repo_name: Odoo Usability
repo_slug: odoo-usability
repo_website: https://github.com/itbrasil-odoo/odoo-usability
use_pyproject_toml: true
use_ruff: true

